### PR TITLE
Add orbiting

### PR DESCRIPTION
**Pull request by ibash**
Adds support for orbiting by holding shift.

Note that this still has a bug if you try to orbit while the eye is at (0, 0, 1).

This also adds code to allow stopping the add-in by switching back the sendEvent method.

### CODE REVIEW

**Comment by Naozumi520** [comment]
I may have misunderstood this pull request, isn't orbiting already supported via hold shifted? I'm new to use this add-on and so far it's working great.

**Comment by pravdomil** [comment]
checking!

**Comment by pravdomil** [comment]
check new https://github.com/mertrois/Native-Trackpad/releases

**Comment by pravdomil** [comment]
works great!!

how to do

zoom at cursor position?

rotate around cursor position?

**Comment by pravdomil** [comment]
image

use perspective camera

use top view

try rotate

now Y axis is not facing up

how to fix that?

**Pull request closed without merging**
