### PR TITLE
Added SmartMagnify

### PR DESCRIPTION
**Pull request by gjastrebski**
Updated to support two-finger double-tap to smart zoom to fit

### CODE REVIEW

**Comment by pravdomil** [comment]
how did you test it? on version from appstore?

**Comment by gjastrebski** [comment]
Built the dylib locally, and copied it into the NativeTrackpad, install from the AppStore

**Comment by pravdomil** [comment]
well my AppStore Fusion 360 stopped working

and the new Fusion 360 seems to broke the plugin, I have no idea why, I'm not going to fix it

 anyways thanks for your contribution

**Comment by gjastrebski** [comment]
I downloaded fusion 360 directly from AD, installed the plugin from the fusion plugin store, and replaced the dylib, and it all worked

**Pull request merged**
